// AUTO-GENERATED by the docchain CLI. Do not edit by hand.
//
// Each installed module contributes one static import + one entry in the
// array. Starts empty — plugins add themselves here when installed (via
// symlink for dev, copy for prod). The bundler tree-shakes disabled
// modules to zero bytes.
//
// Until the CLI lands, this file is hand-maintained by the install step.

import type { ModuleManifest } from "./types";

export const registry: ModuleManifest[] = [];
